### ISSUE TITLE
Sensu-Plugins Thoughts

### ISSUE THREAD

**Issue by mattyjones** [sensu-plugins/sensu-plugins-rethinkdb#1]
@jatsrt 

What are your thoughts on folding this in to an offical community plugin?

I would be more than happy to work with on on getting this released officially and bringing it into the Sensu-Plugins org.  If you wanted to we can always just drop a mention of this somewhere and you can keep it in your repo.  I am open to discussion on this.

**Comment by jatsrt** [comment]
Would love to see this as an official plugin.  No need to keep it here.

**Comment by mattyjones** [comment]
Ok, well for starters, you can transfer the project to me (mattyjones) and I will then add it to the org.  We can then create an issue with a checklist of what would be needed to build and deploy this as a gem and go from there!

**Comment by jatsrt** [comment]
ok, I also already pushed a gem up to rubygems.org, but I'm sure we can undo that when it is time.  How do you manage outside committers?  Fork and pull request?

**Comment by mattyjones** [comment]
The gem is not a problem.  As of now yes we ask people to fork and pr.  There are plans in the wroks when GH drops its new stuff to add individuals to specific repos vs to teams that have access to all repos.
