### ISSUE TITLE
Enable rubygems deploys

### ISSUE THREAD

**Issue by eheydrick** [sensu-plugins/sensu-plugins-rethinkdb#2]
@jatsrt can you add sensu-plugin@sensu-plugins.io as an owner of the sensu-plugins-rethinkdb gem. I'd like to get deploys going from here.

**Comment by majormoses** [comment]
https://travis-ci.org/sensu-plugins/sensu-plugins-rethinkdb/jobs/253979899#L365

**Comment by eheydrick** [comment]
I've reached out to Jake via e-mail. Hopefully we'll have access soon.

**Comment by jatsrt** [comment]
Sorry for missing this initially.  You should be added now.  Let me know if you are not.

**Comment by jatsrt** [comment]
Also, after you confirm that you have ownership, please feel free to remove my account from it.  Glad to see this is still alive!

**Comment by majormoses** [comment]
Awesome, I reran the existing trasvis build and it released sucessfully: https://rubygems.org/gems/sensu-plugins-rethinkdb/versions/1.0.0

**Comment by eheydrick** [comment]
Thanks @jatsrt!
